# Makefile for HELLO1.CPP
# Copyright 1992,1996 Paul DiLascia
#

CL = bcc32.exe
RC = brc32.exe
LINK = bcc32.exe
CFLAGS = -c -w-par -tW -DWIN32_LEAN_AND_MEAN 
LFLAGS = -tW

.cpp.obj:
	$(CL) $(CFLAGS) $<

.rc.res:
	$(RC) -r $<

hello1.exe: wpwin.obj hello1.obj hello1.res
	$(LINK) $(LFLAGS) hello1.obj wpwin.obj
	$(RC) hello1.res

hello1.obj : hello1.cpp
wpwin.obj : wpwin.h wprect.h wppdefs.h wpwin.cpp

clean:
	del *.obj *.exe *.res
